---
version: "3.3"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
        #- PASSWORD=password #optional
        #- HASHED_PASSWORD= #optional
        #- SUDO_PASSWORD=password #optional
        #- SUDO_PASSWORD_HASH= #optional
        #- PROXY_DOMAIN=code-server.my.domain #optional
        #- DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ${DATA}/code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped


  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      #- DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DATA}/deluge/config:/config
      - ${MEDIA}/downloads:/downloads 
    ports:
      - 8112:8112
      #- 6881:6881
      #- 6881:6881/udp
    restart: unless-stopped


  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ${DATA}/homer/data:/www/assets
    ports:
      - 80:8080
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - AUTO_UPDATE=true #optional
        #- RUN_OPTS=<run options here> #optional
    volumes:
      - ${DATA}/jackett/config:/config
      - ${DATA}/jackett/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:  
      - PUID=1000                            
      - PGID=1000                                  
      - TZ=America/Montreal                                          
        #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional                                               
    volumes:
      - ${DATA}/jellyfin/config:/config                                                            
      - ${MEDIA}/tvshows:/tvshows                                                
      - ${MEDIA}/movies:/movies                                                  
    ports:                                                                                      
      - 8096:8096                                                                                               
      #- 8920:8920 #optional                                                                                   
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - ${DATA}/radarr/config:/config
      - ${MEDIA}/movies:/movies
      - ${MEDIA}/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DATA}/readarr/config:/config
      - ${MEDIA}/books:/books #optional
      - ${MEDIA}/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

      #nzbget:
      #image: lscr.io/linuxserver/nzbget:latest
      #container_name: nzbget
      #environment:
      #- PUID=1000
      #- PGID=1000
      #- NZBGET_USER=nzbget #optional
      #- NZBGET_PASS=tegbzn6789 #optional
      #volumes:
      #- ${DATA}/nzbget/config:/config
      #- ${MEDIA}/downloads:/downloads #optiona
      #- ${MEDIA}/books:/books
      #ports:
      #- 6789:6789
      #restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
        #- TZ=Europe/London
    volumes:
      - ${DATA}/sabnzbd/config:/config
      - ${MEDIA}/downloads/complete:/downloads #optional
      - ${MEDIA}/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8033:8033
    restart: unless-stopped

  openbooks:
    ports:
      - 8070:8070
      - 9090:9090
    restart: unless-stopped
    container_name: OpenBooks
    command: --persist
    environment:
      - BASE_PATH=/openbooks/
    image: evanbuss/openbooks:latest
    volumes:
      - ${DATA}/openbooks/config:/config
      - ${MEDIA}/books:/books
